// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package uploadphoto

import (
	"github.com/google/wire"
	"latihan/app"
	"latihan/infrastructure/configuration"
)

// Injectors from wire.go:

func InjectRoutes() (*Routes, error) {
	appEnvironment, err := app.ProvideAppEnvironment()
	if err != nil {
		return nil, err
	}
	appLog := app.ProvideLogger(appEnvironment)
	environmentConfigBinderProperties := _wireEnvironmentConfigBinderPropertiesValue
	appConfig := app.ProvideAppConfig(environmentConfigBinderProperties)
	db := app.ProvidePostgre(appConfig)
	repository := NewRepository(db)
	service := NewService(appConfig, appLog, repository)
	iService := app.ProvideActivityLogger(appConfig)
	delivery := NewDelivery(appLog, service, iService)
	routes := NewRoutes(delivery)
	return routes, nil
}

var (
	_wireEnvironmentConfigBinderPropertiesValue = configuration.EnvironmentConfigBinderProperties{
		FileName: "app-config",
		Path:     "./env",
	}
)

// wire.go:

var (
	ModuleSets = wire.NewSet(
		NewRepository, wire.Bind(new(IRepository), new(*Repository)), NewService, wire.Bind(new(IService), new(*Service)), NewDelivery,
		NewRoutes)
)
